"""create entitlements and leases tables

Revision ID: b5da84864b3d
Revises: 
Create Date: 2025-09-25 21:43:01.331538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5da84864b3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entitlements',
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('blob_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('leases',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('product', sa.String(length=64), nullable=False),
    sa.Column('machine_fingerprint', sa.String(length=256), nullable=False),
    sa.Column('issued_at', sa.String(length=64), nullable=False),
    sa.Column('lease_until', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_leases_customer_id'), 'leases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_leases_machine_fingerprint'), 'leases', ['machine_fingerprint'], unique=False)
    op.create_index(op.f('ix_leases_product'), 'leases', ['product'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leases_product'), table_name='leases')
    op.drop_index(op.f('ix_leases_machine_fingerprint'), table_name='leases')
    op.drop_index(op.f('ix_leases_customer_id'), table_name='leases')
    op.drop_table('leases')
    op.drop_table('entitlements')
    # ### end Alembic commands ###
