name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    env:
      PYTHONPATH: .
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (locked)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.lock

      - name: Run pytest
        run: pytest -q
